services:
    # Обработчики
    werkint.sprites.controller:
        class: Werkint\Bundle\SpritesBundle\EventListener\ControllerLoader
        arguments:
            - @werkint.webapp
            - %werkint_sprites%
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelController }

    werkint.sprites:
        class: Werkint\Bundle\SpritesBundle\Service\Sprites
        arguments:
            - @event_dispatcher
            - %werkint_sprites%
            - %werkint_sprites_template%
    werkint.sprites.compileprovider:
        class: Werkint\Bundle\SpritesBundle\Service\CompileProvider
        arguments:
            - @werkint.sprites
        tags:
            - { name: werkint.compile.provider, class: werkint.sprites }
    # Twig
    werkint.sprites.twigappextension:
        class: Werkint\Bundle\SpritesBundle\Service\TwigExtension
        arguments:
            - %werkint_sprites_namespace%
        tags:
            - { name: twig.extension }